#!/bin/bash
shopt -s extglob nullglob
OPTS=
case "$1" in
  @(*@)@([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\
.@([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\
.@([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\
.@([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]))
    echo "IP address detected, will use temporary file" 2>&1
    OPTS="-o UserKnownHostsFile=~/.ssh/known_hosts_temp -o StrictHostKeyChecking=no"
    rm -f ~/.ssh/known_hosts_temp
    ;;
esac

exec /usr/bin/ssh $OPTS "$@"
